### PR TITLE
Issue #14: Add community evaluation survey

### PR DESCRIPTION
**Pull request by nengard**
This is a rough draft of the survey to start.

### CODE REVIEW

**Comment by pmkovar** [comment]
@nengard You may want to include the new file in master files so that it is built.

**Comment by nengard** [comment]
Will do @pmkovar !

**Comment by nengard** [comment]
@pmkovar any other feedback on this? Think it's okay to merge? I'd like to do it before we change the directory structure.

**Comment by pmkovar** [comment]
@nengard No other feedback, feel free to go ahead and merge.

**Pull request merged**
